title: Chris David Miles
description: Developer, builder, and open-source enthusiast.
theme: minima
url: "https://chrisdavidmiles.github.io"

author: Chris David Miles
github_username: chrisdavidmiles
twitter_username: chrisdavidmiles
mastodon:
  - username: chrisdavidmiles
    instance: mastodon.social
